Correct the format of the SyncErr.json file to match what is expected
iTwin/connector-framework pull request #137
Opened 2024-08-29 22:37 UTC by jchick-bentley

The goals of this PR are:
1. Correct the format of the SyncErr.json file to match what is expected.

ref. [Transmission Format](https://github.com/iTwin/connector-errors/tree/master?tab=readme-ov-file#transmission-format)

3. Look up knowledgebase links and other properties from [fatal-errors.json](https://github.com/iTwin/connector-errors/blob/master/fatal-errors.json)

2024-09-03 10:48 UTC, jffmarker requested changes

2024-09-03 10:48 UTC, jffmarker commented on assets/fatal-errors.json
I don't think you should include this raw JSON data... if people need this, it's accessible in another [public GH repo](https://github.com/iTwin/connector-errors). What you would normally commit is the generated TS file from the internal scripts... this is what the code would then utilize.

2024-09-03 10:48 UTC, jffmarker commented on src/BaseConnector.ts
> +    };
This kind of reverse lookup hasn't been necessary for native Connectors so far... so I'm not sure we should try to enforce this here. And actually... because third party Connectors can emit their own specialized errors, it's not really feasible to enforce this anyway.

2024-09-06 20:42 UTC, jchick-bentley commented on assets/fatal-errors.json
@jffmarker - this is fixed. using the generated .ts file instead.

2024-09-06 20:48 UTC, jchick-bentley commented on src/BaseConnector.ts
> +    };
@jffmarker not sure I understand "reverse lookup".  I refactored the existing method to attempt to perform the lookup IF a 'key' parameter is passed to do the lookup of the structured error.  If no key is passed or the passed key isn't found in iModelConnectorErrors.ts, then the properties passed to the method are used.  As we discussed, I added a new method with takes a SyncError object as a parameter and similarly attempts to use the key to do the lookup iModelConnectorErrors.ts.  It also omits the 'dir' parameter.  The baseconnector has a new structuredErrorDir property which defaults the to the dir the imodelDb is in.

2024-09-10 19:51 UTC, jffmarker approved these changes

2024-09-12 17:14 UTC, merged