Add postorder traversal for new atomics API
iTwin/connector-framework pull request #51
Opened 2022-07-07 16:37 UTC by jackson-at-bentley

I'm trying to implement Sam's feedback in an email chain.

```
So, I think your detectDeletedElementsInChannel function needs two things:
-	detect elements that are sub-modeled, and recursively delete the submodel.
-	Detect elements that have children and recursively delete the children.
```

The prior implementation deletes elements that are scoped to their repository link, but that has to be done explicitly by the connector author? `detectChanges` takes a mandatory scope.

There's a whole bunch of changes, because this PR uses my fork with coverage. We can't merge that because I broke the runner API to get the tooling to work, so I'll have to manually integrate any changes into `main`. I want you all to be able to run the (very simple) tests though.

2022-07-07 16:38 UTC, jackson-at-bentley commented on src/Synchronizer.ts
> +  }
I'm failing to delete the model in the last test. I've noticed that the partition id and the model id are the same in the tests, which seems bad.

2022-07-07 16:38 UTC, jackson-at-bentley reviewed
Failing test. ):

2022-07-07 17:05 UTC, swwilson-bsi commented on src/Synchronizer.ts
> +  }
partitionid and modelid are always the same. That's normal. If deleteElement fails, it is probably because element is the target of a foreign key (aka pointer) from some other element. You should be able to tell from the error code that is returned.

2022-07-07 17:47 UTC, jackson-at-bentley commented on src/Synchronizer.ts
> +  }
`deleteModel` is failing with `Wrong Model: error deleting model [error deleting model] id 0x14`. I'm not sure what that means.

If I try to delete the modeled element first, I get `ForeignKey Constraint: Error deleting element [error deleting element], id:0x14`, which makes sense, because the model models it.

2022-07-07 18:04 UTC, swwilson-bsi commented on src/Synchronizer.ts
> +  }
DgnModel::Delete returns DgnDbStatus::WrongModel if the model's "persistent" flag is false. That flag is cleared by DgnModel::DeleteModel itself. So, that indicates that you are deleting the same model twice.

2022-07-07 18:48 UTC, swwilson-bsi commented on src/Synchronizer.ts
> +  }
You are right that m_persistent is set by AddLoadedModel. That function is called by DgnModel::_OnInserted. So, m_persistent is set when a new model is inserted into the iModel. (This is all in [DgnModel.cpp](https://bentleycs.visualstudio.com/iModelTechnologies/_git/imodel02?path=/iModelCore/iModelPlatform/DgnCore/DgnModel.cpp). 

I don't see how you could have a model in iTtwin.js where the native peer object (DgnModel) has not yet been inserted into the iModel.  I suggest that you write some simpler tests that demonstrate that you can create and then delete a model and the modeled element.

2022-07-07 19:46 UTC, jackson-at-bentley commented on src/Synchronizer.ts
> +  }
Thank you so much Sam, you're right. I can't delete models from a snapshot. Is there something about a snapshot that's making native upset?

The good news is hopefully it's just the tests that are broken.

2022-07-07 21:17 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
The minimal test in question, throws the same `WrongModel` error.

2022-07-08 11:52 UTC, swwilson-bsi commented on test/standalone/Synchronizer.test.ts
> +  });
Are you sure that you are calling empty.models.insertModel on the new model inside of makeToyElement?

2022-07-08 15:08 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
[Here's `insertModel`](https://github.com/iTwin/connector-framework/blob/b096214d4c6b8fce3c185638805f1ad655b80baf/test/standalone/Synchronizer.test.ts#L81). The relationships API is a bit sparsely documented, like the requirement to use classes for some embedding relationships, but tracing through the recursion the tree looks like I expect.

2022-07-08 15:49 UTC, swwilson-bsi commented on test/standalone/Synchronizer.test.ts
> +  });
I see now that you are trying to delete a DefinitionPartition/Model. You have to call the special function IModelDb.elements.deleteDefinitionElements to do that.

2022-07-08 16:10 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
Well darn, that was a lucky test. Thank you Sam!

2022-07-08 18:00 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
After some further pondering I'm not able to resolve this test.

The toy element looks like this.

```
fruits subject ➡ fruits definition partition ➡ fruits definition model
```

`DefinitionModel` doesn't inherit from `DefinitionElement`. `DefinitionGroup` does, but those don't exist in this minimal test.

`deleteDefinitionElements` ignores the definition partition because it's not a `DefinitionElement`, so something like the following fails.

```ts
assert.doesNotThrow(() => empty.elements.deleteDefinitionElements([partitionId])); // okay
const definition = empty.elements.tryGetElement(partitionId);
assert.isNotOk(definition); // 💥 boom! expect definition partition to be falsey
```

2022-07-08 18:32 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
I haven't dangled any `DefinitionElement`'s from the `DefinitionModel` in the minimal test. The `DefinitionGroup`'s come from `berryGroups`. I've updated the test, it looks like this now. I'm still getting the `WrongModel` error. Thank you for your time! I'm happy to go ask @akshay-madhukar if GitHub exchanges aren't an efficient use of it.

```ts
it("can delete model", () => {
  // Here's our toy element.

  // fruits subject ➡ fruits definition partition ➡ fruits definition model

  // Try to delete the model first, and then the partition.

  const empty = SnapshotDb.createEmpty(path, { name, rootSubject: { name: root } });
  const [,, partitionId, modelId] = makeToyElement(empty);

  // No definition elements in the model! No need for `deleteDefinitionElements`.
  assert.deepEqual(childrenOfModel(empty, modelId), []);

  assert.doesNotThrow(() => empty.models.deleteModel(modelId)); // 💥 boom! wrong model
  assert.doesNotThrow(() => empty.elements.deleteElement(partitionId));

  const partition = empty.elements.tryGetElement(partitionId);
  assert.isNotOk(partition);

  const model = empty.models.tryGetModel(modelId);
  assert.isNotOk(model);
});
```

2022-07-08 18:43 UTC, swwilson-bsi commented on test/standalone/Synchronizer.test.ts
> +  });
I don't see where you are deleting the elements in the definition model that you are trying to delete. Maybe Akshay can help, if he's closer.

2022-07-08 18:53 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
The model is empty in this test. It has no elements. Is that a problem?

2022-07-08 18:56 UTC, swwilson-bsi commented on test/standalone/Synchronizer.test.ts
> +  });
No. That is not a problem. I suggest that you ask Keith Bentley or Paul Connelly why you are getting the WrongModel exception on a SnapshotDb.

2022-07-11 18:11 UTC, jackson-at-bentley commented on test/standalone/Synchronizer.test.ts
> +  });
At some point during our discussion I conflated `DefinitionModel` with `DictionaryModel`, which I was using in my tests because I thought it would be fun. According to the documentation and my and Jason's understanding, this model is a singleton, indestructible container that's owned by the repository, so it doesn't make sense for it to model anything but the root subject.

> The singleton container for repository-specific definition elements.

I'm marking this as resolved. Thank you for your time Sam and bearing a silly mistake.

2022-07-11 18:19 UTC, swwilson-bsi commented on test/standalone/Synchronizer.test.ts
> +  });
It's great that you figured it out.

2022-07-12 22:25 UTC, jchick-bentley requested changes

2022-07-12 22:25 UTC, jchick-bentley commented on src/Synchronizer.ts
> +    // TODO: makeRepositoryLink can't return undefined.
by 'can't' do you mean it's impossible and therefore you're commenting out this test b/c it's unnecessary OR should we throw an error here?

2022-07-12 22:25 UTC, jchick-bentley commented on test/standalone/Synchronizer.test.ts
> +      assert.throws(oops, IModelError, /missing id/i);
pls. add comment w/ reference to chai documentation to explain the use of regex here. https://www.chaijs.com/api/assert/#method_assert

2022-07-13 16:13 UTC, jackson-at-bentley commented on src/Synchronizer.ts
> +    // TODO: makeRepositoryLink can't return undefined.
`createElement` in `makeRepositoryLink` throws. The return type of `makeRepositoryLink` is a `RepositoryLink` that's been narrowed (in type) to an `Element`.

We're not using TypeScript's strict mode, that's been added in the `coverage` branch that's now merged. I think the author may have been trying to guard against `strictNullChecks` but I'm not sure.

2022-07-15 19:58 UTC, jackson-at-bentley commented
Closing, will reopen with the commits from `main` so it's not as difficult to follow.

2022-07-15 19:58 UTC, closed without merging