Rewrite synchronizer deletion and add locking changes in runner
iTwin/connector-framework pull request #55
Opened 2022-07-15 20:46 UTC by jackson-at-bentley

Apparently I can't escape the merge commit of the testing infrastructure. I'm sorry for the mile-long commit history.

This PR contains the two changes from Sam's email feedback.
1. Instead of using the synchronizer's cache to find elements that are scoped to a given repository link, we do a postorder traversal of the iModel starting at the root subject and delete elements we haven't seen and empty models. My hope is that the `ExternalSourceAspect`'s are cleaned up because of their embedding relationship (Figure 1). I don't think the repository links and external sources are cleaned up.
2. The runner has been rewritten to use the new locking API.

Unfortunately the two tests in #standalone and #integration that make an update pass with the synchronizer are now both failing because the iModel is ripped to shreds by the new deletion algorithm. I'm not sure if my deletion function is incorrect or not handling edge cases, but I'm concerned that the `TestConnector` bypasses the synchronizer's `updateIModel` function in quite a few places and so the synchronizer doesn't know they're still in the source file. I've not yet been able to fix the connector.

---

Okay, this marks the start of a bit of a rant. Hopefully it reflects an incorrect understanding of the framework.

In my opinion, the `TestConnector` indicates a larger problem with the synchronizer's current API.

- It seems to operate under the philosophy that the connector author is responsible for the intermediate representation of the iModel, but requires them to feed it `SynchronizationResults`, which are trees of elements. All of the children of such a tree do not have provenance information, and the synchronizer ignores their change state. If it detects that the parent has changed, it will fall into a recursive update of the children (`updateResultsInIModelForChildren` seems to be buggy).
- An update requires the iModel ID of the element, not the identifier that anchors it to the source document in its `ExternalSourceAspect`. The author shouldn't be responsible for providing that ID, because we have the element's provenance information.
- I think as Zach noticed, the synchronizer goes only halfway towards defining an intermediate representation and ignores models.

Like Jeff said, the synchronizer is the minimal set of tools needed to map a source file to an iModel. It's super important. I think it needs a new API. We don't have to be as opinionated as PCF (defining loaders, relationship nodes), but I think we should move closer towards it and provide an intermediate representation. We already have such objects: they're defined in iTwin. With a bit of declaration merging in TypeScript, we can present the synchronizer with element properties and provenance and let it do its thing.

### Figure 1

<img alt="A diagram of the elements of an iModel for which the synchronizer is reponsible" src="https://user-images.githubusercontent.com/107633044/179303737-f092e194-128b-4287-8814-eb1706fe048a.png">

2022-07-18 16:44 UTC, jchick-bentley requested changes

2022-07-22 16:23 UTC, jackson-at-bentley commented on src/Synchronizer.ts
> +    // TODO: This if statement throws. We can't recover from this, so we let it explode the
If the backend fails to perform a deletion should we continue? I'm not sure what would cause the underlying database to fail to perform an operation, but that sounds bad. `deleteInChannel` will throw if the backend throws.

2022-07-22 17:00 UTC, swwilson-bsi commented on src/Synchronizer.ts
> +    // TODO: This if statement throws. We can't recover from this, so we let it explode the
We should fail.

2022-07-22 17:42 UTC, jackson-at-bentley commented
A few concerns:
- Are there any other embedding relationships or dependencies that will cause the SQLite database to buck us during the traversal?
- Cleaning up may take multiple runs, for example, if a geometry stream depends on a definition element and the geometry stream is visited first.
- Deleting definition elements is really expensive and shouldn't be done individually.

2022-07-27 20:25 UTC, akshay-madhukar approved these changes

2022-07-27 20:57 UTC, jchick-bentley commented on src/Synchronizer.ts
> +    // TODO: This if statement throws. We can't recover from this, so we let it explode the
@jackson-at-bentley was any action taken on this?

2022-07-27 21:38 UTC, jchick-bentley approved these changes

2022-07-27 21:38 UTC, merged